BEGIN
    FOR DATA IN (
        SELECT C.NAME,L.LOANID,L.ENDDATE
         FROM CUSTOMERS C JOIN LOANS L
        ON C.CUSTOMERID=L.CUSTOMERID
        WHERE L.ENDDATE BETWEEN SYSDATE AND SYSDATE+30
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            'DEAR CUSTOMER '||
            DATA.NAME|| ', YOUR LOAN ID '||
            DATA.LOANID || ' IS DUE ON '||
            TO_CHAR(DATA.ENDDATE,'DD-MM-YYYY')
        );
    END LOOP;
END;