BEGIN
    FOR data in (SELECT CUSTOMERID, BALANCE FROM CUSTOMERS )
    LOOP 
        IF data.BALANCE>1000 THEN
           UPDATE CUSTOMERS SET ISVIP=TRUE WHERE CUSTOMERID=DATA.CUSTOMERID;
           DBMS_OUTPUT.PUT_LINE('CUSTOMER CHANGED TO VIP IS '||DATA.CUSTOMERID);
        ELSE
            UPDATE CUSTOMERS SET ISVIP=FALSE WHERE CUSTOMERID=DATA.CUSTOMERID;
        END IF;
    END LOOP;
    COMMIT;
  
END;