CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus(BONUS_PERCENT NUMBER)
IS 
BEGIN 
    UPDATE EMPLOYEES SET SALARY=(SALARY+SALARY*BONUS_PERCENT);
    DBMS_OUTPUT.PUT_LINE('UPDATED SALARY OF EMPLOYEES - HIKE OF '||BONUS_PERCENT);
    COMMIT;
END;