CREATE OR REPLACE PROCEDURE TransferFunds(
    ACCNO_FROM NUMBER,
    ACCNO_TO NUMBER,
    AMT NUMBER
)
IS
 A_BALANCE NUMBER;
BEGIN
     SELECT BALANCE INTO A_BALANCE FROM ACCOUNTS WHERE ACCOUNTID=ACCNO_FROM;
     IF A_BALANCE>=AMT THEN
        UPDATE ACCOUNTS SET BALANCE =BALANCE-AMT WHERE ACCOUNTID=ACCNO_FROM;
         DBMS_OUTPUT.PUT_LINE('AMT DEBITED SUCCESSFUL');

        UPDATE ACCOUNTS SET BALANCE =BALANCE+AMT WHERE ACCOUNTID=ACCNO_TO;
         DBMS_OUTPUT.PUT_LINE('AMT CREDITED SUCCESSFUL');
                COMMIT;

     ELSE
       DBMS_OUTPUT.PUT_LINE('INSUFFICIENT BALANCE');
     END IF;


EXCEPTION
 WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE(
            'Account Not Found'
        );

    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE(
            'Error: ' || SQLERRM
        );
  

END;




BEGIN

    TransferFunds(2, 1, 1000);

END;

SELECT * FROM ACCOUNTS;