CREATE OR REPLACE PROCEDURE ProcessMonthlyInterest 
IS
BEGIN
    UPDATE ACCOUNTS SET BALANCE = BALANCE*0.01 WHERE ACCOUNTTYPE='Savings';
    DBMS_OUTPUT.PUT_LINE('UPDATED BALANCE OF SAVINGS ACCOUNTS');
    COMMIT;
END;